[platformio]
src_dir = .

[env:tbeam-s3-supreme]
platform      = espressif32
board         = esp32-s3-devkitc-1
framework     = arduino
monitor_speed = 115200
lib_ldf_mode  = chain
lib_deps =
    jgromes/RadioLib @ ^6.6.0
    mikalhart/TinyGPSPlus @ ^1.0.3
    lewisxhe/XPowersLib @ ^0.2.6
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
