[platformio]
src_dir = .

[env:ttgo-lora32-v1]
platform      = espressif32
board         = ttgo-lora32-v1
framework     = arduino
monitor_speed = 115200
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    sandeepmistry/LoRa @ ^0.8.0
build_flags =
    -I../common
